"""Finance permission constants."""

FINANCE_PERMISSIONS: list[tuple[str, str, str, str]] = [
    ("finance.coa:read", "finance.coa", "read", "finance"),
    ("finance.coa:create", "finance.coa", "create", "finance"),
    ("finance.coa:update", "finance.coa", "update", "finance"),
    ("finance.coa:delete", "finance.coa", "delete", "finance"),
    ("finance.fiscal_year:read", "finance.fiscal_year", "read", "finance"),
    ("finance.fiscal_year:create", "finance.fiscal_year", "create", "finance"),
    ("finance.fiscal_year:close", "finance.fiscal_year", "close", "finance"),
    ("finance.period:read", "finance.period", "read", "finance"),
    ("finance.period:close", "finance.period", "close", "finance"),
    ("finance.period:reopen", "finance.period", "reopen", "finance"),
    ("finance.journal:read", "finance.journal", "read", "finance"),
    ("finance.journal:create", "finance.journal", "create", "finance"),
    ("finance.journal:update", "finance.journal", "update", "finance"),
    ("finance.journal:delete", "finance.journal", "delete", "finance"),
    ("finance.journal:submit", "finance.journal", "submit", "finance"),
    ("finance.journal:approve", "finance.journal", "approve", "finance"),
    ("finance.journal:post", "finance.journal", "post", "finance"),
    ("finance.journal:adjust", "finance.journal", "adjust", "finance"),
    ("finance.journal:reverse", "finance.journal", "reverse", "finance"),
    ("finance.gl:read", "finance.gl", "read", "finance"),
    ("finance.ar:read", "finance.ar", "read", "finance"),
    ("finance.ar:create", "finance.ar", "create", "finance"),
    ("finance.ar:payment", "finance.ar", "payment", "finance"),
    ("finance.ap:read", "finance.ap", "read", "finance"),
    ("finance.ap:create", "finance.ap", "create", "finance"),
    ("finance.ap:payment", "finance.ap", "payment", "finance"),
    ("finance.ap:approve", "finance.ap", "approve", "finance"),
    ("finance.tax:read", "finance.tax", "read", "finance"),
    ("finance.tax:report", "finance.tax", "report", "finance"),
    ("finance.currency_rate:read", "finance.currency_rate", "read", "finance"),
    ("finance.currency_rate:create", "finance.currency_rate", "create", "finance"),
    ("finance.currency_rate:update", "finance.currency_rate", "update", "finance"),
    ("finance.asset_transaction:read", "finance.asset_transaction", "read", "finance"),
    ("finance.asset_transaction:create", "finance.asset_transaction", "create", "finance"),
    ("finance.asset_transaction:post", "finance.asset_transaction", "post", "finance"),
    ("finance.report:read", "finance.report", "read", "finance"),
    ("finance.report:export", "finance.report", "export", "finance"),
]

FINANCE_ACCOUNTANT_PERMISSIONS = [
    "finance.coa:read",
    "finance.journal:read",
    "finance.journal:create",
    "finance.journal:update",
    "finance.journal:submit",
    "finance.gl:read",
    "finance.ar:read",
    "finance.ar:create",
    "finance.ap:read",
    "finance.ap:create",
    "finance.currency_rate:read",
    "finance.period:read",
    "finance.fiscal_year:read",
    "finance.report:read",
]

FINANCE_MANAGER_PERMISSIONS = FINANCE_ACCOUNTANT_PERMISSIONS + [
    "finance.journal:approve",
    "finance.period:close",
    "finance.ap:approve",
    "finance.ap:payment",
    "finance.ar:payment",
    "finance.tax:read",
    "finance.tax:report",
]

CFO_PERMISSIONS = [p[0] for p in FINANCE_PERMISSIONS]
