"""BPM permission constants — Phase 1 + 1.5 + 2A + 2B."""

BPM_PERMISSIONS: list[tuple[str, str, str, str]] = [
    ("bpm.category:read", "bpm.category", "read", "bpm"),
    ("bpm.category:create", "bpm.category", "create", "bpm"),
    ("bpm.category:update", "bpm.category", "update", "bpm"),
    ("bpm.category:delete", "bpm.category", "delete", "bpm"),
    ("bpm.category:archive", "bpm.category", "archive", "bpm"),
    ("bpm.category:restore", "bpm.category", "restore", "bpm"),
    ("bpm.template:read", "bpm.template", "read", "bpm"),
    ("bpm.template:create", "bpm.template", "create", "bpm"),
    ("bpm.template:update", "bpm.template", "update", "bpm"),
    ("bpm.template:copy", "bpm.template", "copy", "bpm"),
    ("bpm.template:archive", "bpm.template", "archive", "bpm"),
    ("bpm.template:restore", "bpm.template", "restore", "bpm"),
    ("bpm.template:export", "bpm.template", "export", "bpm"),
    ("bpm.template:import", "bpm.template", "import", "bpm"),
    ("bpm.definition:read", "bpm.definition", "read", "bpm"),
    ("bpm.definition:create", "bpm.definition", "create", "bpm"),
    ("bpm.definition:update", "bpm.definition", "update", "bpm"),
    ("bpm.definition:archive", "bpm.definition", "archive", "bpm"),
    ("bpm.definition:restore", "bpm.definition", "restore", "bpm"),
    ("bpm.version:read", "bpm.version", "read", "bpm"),
    ("bpm.version:create", "bpm.version", "create", "bpm"),
    ("bpm.version:update", "bpm.version", "update", "bpm"),
    ("bpm.version:publish", "bpm.version", "publish", "bpm"),
    ("bpm.version:retire", "bpm.version", "retire", "bpm"),
    ("bpm.version:clone", "bpm.version", "clone", "bpm"),
    ("bpm.version:compare", "bpm.version", "compare", "bpm"),
    ("bpm.version:validate", "bpm.version", "validate", "bpm"),
    ("bpm.dashboard:read", "bpm.dashboard", "read", "bpm"),
    ("bpm.node:read", "bpm.node", "read", "bpm"),
    ("bpm.node:create", "bpm.node", "create", "bpm"),
    ("bpm.node:update", "bpm.node", "update", "bpm"),
    ("bpm.node:delete", "bpm.node", "delete", "bpm"),
    ("bpm.transition:read", "bpm.transition", "read", "bpm"),
    ("bpm.transition:create", "bpm.transition", "create", "bpm"),
    ("bpm.transition:update", "bpm.transition", "update", "bpm"),
    ("bpm.transition:delete", "bpm.transition", "delete", "bpm"),
    ("bpm.graph:validate", "bpm.graph", "validate", "bpm"),
    ("bpm.decision_table:read", "bpm.decision_table", "read", "bpm"),
    ("bpm.decision_table:create", "bpm.decision_table", "create", "bpm"),
    ("bpm.decision_table:update", "bpm.decision_table", "update", "bpm"),
    ("bpm.decision_table:delete", "bpm.decision_table", "delete", "bpm"),
    ("bpm.decision_table:enable", "bpm.decision_table", "enable", "bpm"),
    ("bpm.decision_table:disable", "bpm.decision_table", "disable", "bpm"),
    ("bpm.business_rule:read", "bpm.business_rule", "read", "bpm"),
    ("bpm.business_rule:create", "bpm.business_rule", "create", "bpm"),
    ("bpm.business_rule:update", "bpm.business_rule", "update", "bpm"),
    ("bpm.business_rule:delete", "bpm.business_rule", "delete", "bpm"),
    ("bpm.variable:read", "bpm.variable", "read", "bpm"),
    ("bpm.variable:create", "bpm.variable", "create", "bpm"),
    ("bpm.variable:update", "bpm.variable", "update", "bpm"),
    ("bpm.variable:delete", "bpm.variable", "delete", "bpm"),
    ("bpm.form_reference:read", "bpm.form_reference", "read", "bpm"),
    ("bpm.form_reference:create", "bpm.form_reference", "create", "bpm"),
    ("bpm.form_reference:update", "bpm.form_reference", "update", "bpm"),
    ("bpm.form_reference:delete", "bpm.form_reference", "delete", "bpm"),
    ("bpm.assignment_rule:read", "bpm.assignment_rule", "read", "bpm"),
    ("bpm.assignment_rule:create", "bpm.assignment_rule", "create", "bpm"),
    ("bpm.assignment_rule:update", "bpm.assignment_rule", "update", "bpm"),
    ("bpm.assignment_rule:delete", "bpm.assignment_rule", "delete", "bpm"),
    ("bpm.escalation_policy:read", "bpm.escalation_policy", "read", "bpm"),
    ("bpm.escalation_policy:create", "bpm.escalation_policy", "create", "bpm"),
    ("bpm.escalation_policy:update", "bpm.escalation_policy", "update", "bpm"),
    ("bpm.escalation_policy:delete", "bpm.escalation_policy", "delete", "bpm"),
    ("bpm.sla_policy:read", "bpm.sla_policy", "read", "bpm"),
    ("bpm.sla_policy:create", "bpm.sla_policy", "create", "bpm"),
    ("bpm.sla_policy:update", "bpm.sla_policy", "update", "bpm"),
    ("bpm.sla_policy:delete", "bpm.sla_policy", "delete", "bpm"),
    ("bpm.trigger:read", "bpm.trigger", "read", "bpm"),
    ("bpm.trigger:create", "bpm.trigger", "create", "bpm"),
    ("bpm.trigger:update", "bpm.trigger", "update", "bpm"),
    ("bpm.trigger:delete", "bpm.trigger", "delete", "bpm"),
    ("bpm.trigger:enable", "bpm.trigger", "enable", "bpm"),
    ("bpm.trigger:disable", "bpm.trigger", "disable", "bpm"),
    ("bpm.notification_template:read", "bpm.notification_template", "read", "bpm"),
    ("bpm.notification_template:create", "bpm.notification_template", "create", "bpm"),
    ("bpm.notification_template:update", "bpm.notification_template", "update", "bpm"),
    ("bpm.notification_template:delete", "bpm.notification_template", "delete", "bpm"),
    ("bpm.notification_template:enable", "bpm.notification_template", "enable", "bpm"),
    ("bpm.notification_template:disable", "bpm.notification_template", "disable", "bpm"),
    ("bpm.instance:read", "bpm.instance", "read", "bpm"),
    ("bpm.instance:create", "bpm.instance", "create", "bpm"),
    ("bpm.instance:update", "bpm.instance", "update", "bpm"),
    ("bpm.instance:delete", "bpm.instance", "delete", "bpm"),
    ("bpm.instance:start", "bpm.instance", "start", "bpm"),
    ("bpm.instance:cancel", "bpm.instance", "cancel", "bpm"),
    ("bpm.instance:suspend", "bpm.instance", "suspend", "bpm"),
    ("bpm.instance:resume", "bpm.instance", "resume", "bpm"),
    ("bpm.instance:complete", "bpm.instance", "complete", "bpm"),
    ("bpm.instance:fail", "bpm.instance", "fail", "bpm"),
    ("bpm.task:read", "bpm.task", "read", "bpm"),
    ("bpm.task:create", "bpm.task", "create", "bpm"),
    ("bpm.task:update", "bpm.task", "update", "bpm"),
    ("bpm.task:delete", "bpm.task", "delete", "bpm"),
    ("bpm.task:assign", "bpm.task", "assign", "bpm"),
    ("bpm.task:claim", "bpm.task", "claim", "bpm"),
    ("bpm.task:release", "bpm.task", "release", "bpm"),
    ("bpm.task:complete", "bpm.task", "complete", "bpm"),
    ("bpm.task:reject", "bpm.task", "reject", "bpm"),
    ("bpm.history:read", "bpm.history", "read", "bpm"),
    ("bpm.history:append", "bpm.history", "append", "bpm"),
    ("bpm.delegation:read", "bpm.delegation", "read", "bpm"),
    ("bpm.delegation:create", "bpm.delegation", "create", "bpm"),
    ("bpm.delegation:accept", "bpm.delegation", "accept", "bpm"),
    ("bpm.delegation:reject", "bpm.delegation", "reject", "bpm"),
    ("bpm.delegation:expire", "bpm.delegation", "expire", "bpm"),
    ("bpm.delegation:delete", "bpm.delegation", "delete", "bpm"),
    ("bpm.simulation:read", "bpm.simulation", "read", "bpm"),
    ("bpm.simulation:create", "bpm.simulation", "create", "bpm"),
    ("bpm.simulation:update", "bpm.simulation", "update", "bpm"),
    ("bpm.simulation:delete", "bpm.simulation", "delete", "bpm"),
    ("bpm.simulation:run", "bpm.simulation", "run", "bpm"),
    ("bpm.simulation:validate", "bpm.simulation", "validate", "bpm"),
    ("bpm.simulation:cancel", "bpm.simulation", "cancel", "bpm"),
]

_ALL = [p[0] for p in BPM_PERMISSIONS]

BPM_ADMIN_PERMISSIONS = list(_ALL)

PROCESS_DESIGNER_PERMISSIONS = [
    p
    for p in _ALL
    if ":publish" not in p and ":retire" not in p and ":delete" not in p
]

PROCESS_OWNER_PERMISSIONS = [
    p
    for p in _ALL
    if any(
        x in p
        for x in (
            ":read",
            ":publish",
            ":retire",
            ":validate",
            ":compare",
            "bpm.definition:update",
            "bpm.definition:archive",
            "bpm.definition:restore",
            "bpm.template:read",
            "bpm.category:read",
            "bpm.dashboard:read",
            "bpm.node:read",
            "bpm.transition:read",
            "bpm.graph:validate",
            "bpm.decision_table:read",
            "bpm.business_rule:read",
            "bpm.variable:read",
            "bpm.form_reference:read",
            "bpm.assignment_rule:read",
            "bpm.escalation_policy:read",
            "bpm.sla_policy:read",
            "bpm.trigger:read",
            "bpm.notification_template:read",
            "bpm.instance:read",
            "bpm.task:read",
            "bpm.history:read",
            "bpm.delegation:read",
            "bpm.simulation:read",
            "bpm.simulation:run",
            "bpm.simulation:validate",
            "bpm.instance:start",
            "bpm.instance:cancel",
            "bpm.instance:suspend",
            "bpm.instance:resume",
            "bpm.instance:complete",
            "bpm.task:assign",
            "bpm.task:claim",
            "bpm.task:complete",
            "bpm.delegation:accept",
            "bpm.delegation:reject",
        )
    )
]

WORKFLOW_OPERATOR_PERMISSIONS = [p for p in _ALL if ":read" in p]

WORKFLOW_AUDITOR_PERMISSIONS = [p for p in _ALL if ":read" in p]
