"""Manufacturing permission constants per ERD_08 §16.1."""

MFG_PERMISSIONS: list[tuple[str, str, str, str]] = [
    ("manufacturing.bom:read", "manufacturing.bom", "read", "manufacturing"),
    ("manufacturing.bom:create", "manufacturing.bom", "create", "manufacturing"),
    ("manufacturing.bom:update", "manufacturing.bom", "update", "manufacturing"),
    ("manufacturing.bom:submit", "manufacturing.bom", "submit", "manufacturing"),
    ("manufacturing.bom:approve", "manufacturing.bom", "approve", "manufacturing"),
    ("manufacturing.routing:read", "manufacturing.routing", "read", "manufacturing"),
    ("manufacturing.routing:create", "manufacturing.routing", "create", "manufacturing"),
    ("manufacturing.routing:update", "manufacturing.routing", "update", "manufacturing"),
    ("manufacturing.work_center:read", "manufacturing.work_center", "read", "manufacturing"),
    ("manufacturing.work_center:create", "manufacturing.work_center", "create", "manufacturing"),
    ("manufacturing.work_center:update", "manufacturing.work_center", "update", "manufacturing"),
    ("manufacturing.machine:read", "manufacturing.machine", "read", "manufacturing"),
    ("manufacturing.machine:create", "manufacturing.machine", "create", "manufacturing"),
    ("manufacturing.machine:update", "manufacturing.machine", "update", "manufacturing"),
    ("manufacturing.production_order:read", "manufacturing.production_order", "read", "manufacturing"),
    ("manufacturing.production_order:create", "manufacturing.production_order", "create", "manufacturing"),
    ("manufacturing.production_order:update", "manufacturing.production_order", "update", "manufacturing"),
    ("manufacturing.production_order:submit", "manufacturing.production_order", "submit", "manufacturing"),
    ("manufacturing.production_order:release", "manufacturing.production_order", "release", "manufacturing"),
    ("manufacturing.production_order:complete", "manufacturing.production_order", "complete", "manufacturing"),
    ("manufacturing.production_order:close", "manufacturing.production_order", "close", "manufacturing"),
    ("manufacturing.production_order:cancel", "manufacturing.production_order", "cancel", "manufacturing"),
    ("manufacturing.material_issue:read", "manufacturing.material_issue", "read", "manufacturing"),
    ("manufacturing.material_issue:create", "manufacturing.material_issue", "create", "manufacturing"),
    ("manufacturing.material_issue:confirm", "manufacturing.material_issue", "confirm", "manufacturing"),
    ("manufacturing.material_return:read", "manufacturing.material_return", "read", "manufacturing"),
    ("manufacturing.material_return:create", "manufacturing.material_return", "create", "manufacturing"),
    ("manufacturing.material_return:confirm", "manufacturing.material_return", "confirm", "manufacturing"),
    ("manufacturing.production_receipt:read", "manufacturing.production_receipt", "read", "manufacturing"),
    ("manufacturing.production_receipt:create", "manufacturing.production_receipt", "create", "manufacturing"),
    ("manufacturing.production_receipt:confirm", "manufacturing.production_receipt", "confirm", "manufacturing"),
    ("manufacturing.scrap:read", "manufacturing.scrap", "read", "manufacturing"),
    ("manufacturing.scrap:create", "manufacturing.scrap", "create", "manufacturing"),
    ("manufacturing.scrap:submit", "manufacturing.scrap", "submit", "manufacturing"),
    ("manufacturing.scrap:approve", "manufacturing.scrap", "approve", "manufacturing"),
    ("manufacturing.scrap:post", "manufacturing.scrap", "post", "manufacturing"),
    ("manufacturing.wip:read", "manufacturing.wip", "read", "manufacturing"),
    ("manufacturing.variance:read", "manufacturing.variance", "read", "manufacturing"),
    ("manufacturing.variance:post", "manufacturing.variance", "post", "manufacturing"),
    ("manufacturing.report:read", "manufacturing.report", "read", "manufacturing"),
    ("manufacturing.report:export", "manufacturing.report", "export", "manufacturing"),
]

SHOP_FLOOR_OPERATOR_PERMISSIONS = [
    "manufacturing.bom:read",
    "manufacturing.routing:read",
    "manufacturing.work_center:read",
    "manufacturing.machine:read",
    "manufacturing.machine:update",
    "manufacturing.production_order:read",
    "manufacturing.material_issue:read",
    "manufacturing.material_issue:create",
    "manufacturing.material_issue:confirm",
    "manufacturing.material_return:read",
    "manufacturing.material_return:create",
    "manufacturing.material_return:confirm",
    "manufacturing.production_receipt:read",
    "manufacturing.production_receipt:create",
    "manufacturing.production_receipt:confirm",
    "manufacturing.scrap:read",
    "manufacturing.scrap:create",
    "manufacturing.wip:read",
]

PRODUCTION_ENGINEER_PERMISSIONS = SHOP_FLOOR_OPERATOR_PERMISSIONS + [
    "manufacturing.bom:create",
    "manufacturing.bom:update",
    "manufacturing.bom:submit",
    "manufacturing.routing:create",
    "manufacturing.routing:update",
    "manufacturing.work_center:create",
    "manufacturing.work_center:update",
    "manufacturing.machine:create",
    "manufacturing.production_order:create",
    "manufacturing.production_order:update",
    "manufacturing.report:read",
]

PRODUCTION_SUPERVISOR_PERMISSIONS = PRODUCTION_ENGINEER_PERMISSIONS + [
    "manufacturing.production_order:submit",
    "manufacturing.production_order:complete",
    "manufacturing.scrap:submit",
    "manufacturing.scrap:approve",
    "manufacturing.variance:read",
]

PRODUCTION_MANAGER_PERMISSIONS = PRODUCTION_SUPERVISOR_PERMISSIONS + [
    "manufacturing.bom:approve",
    "manufacturing.production_order:release",
    "manufacturing.production_order:close",
    "manufacturing.production_order:cancel",
    "manufacturing.scrap:post",
    "manufacturing.variance:post",
    "manufacturing.report:export",
]
