"""Sales permission constants."""

SALES_PERMISSIONS: list[tuple[str, str, str, str]] = [
    ("sales.price_list:read", "sales.price_list", "read", "sales"),
    ("sales.price_list:create", "sales.price_list", "create", "sales"),
    ("sales.price_list:update", "sales.price_list", "update", "sales"),
    ("sales.price_list:delete", "sales.price_list", "delete", "sales"),
    ("sales.discount_rule:read", "sales.discount_rule", "read", "sales"),
    ("sales.discount_rule:create", "sales.discount_rule", "create", "sales"),
    ("sales.discount_rule:update", "sales.discount_rule", "update", "sales"),
    ("sales.discount_rule:delete", "sales.discount_rule", "delete", "sales"),
    ("sales.discount_rule:submit", "sales.discount_rule", "submit", "sales"),
    ("sales.discount_rule:approve", "sales.discount_rule", "approve", "sales"),
    ("sales.customer_credit:read", "sales.customer_credit", "read", "sales"),
    ("sales.customer_credit:create", "sales.customer_credit", "create", "sales"),
    ("sales.customer_credit:update", "sales.customer_credit", "update", "sales"),
    ("sales.quotation:read", "sales.quotation", "read", "sales"),
    ("sales.quotation:create", "sales.quotation", "create", "sales"),
    ("sales.quotation:update", "sales.quotation", "update", "sales"),
    ("sales.quotation:delete", "sales.quotation", "delete", "sales"),
    ("sales.quotation:submit", "sales.quotation", "submit", "sales"),
    ("sales.quotation:approve", "sales.quotation", "approve", "sales"),
    ("sales.quotation:convert", "sales.quotation", "convert", "sales"),
    ("sales.quotation:reject", "sales.quotation", "reject", "sales"),
    ("sales.order:read", "sales.order", "read", "sales"),
    ("sales.order:create", "sales.order", "create", "sales"),
    ("sales.order:update", "sales.order", "update", "sales"),
    ("sales.order:delete", "sales.order", "delete", "sales"),
    ("sales.order:submit", "sales.order", "submit", "sales"),
    ("sales.order:confirm", "sales.order", "confirm", "sales"),
    ("sales.order:cancel", "sales.order", "cancel", "sales"),
    ("sales.order:credit_override", "sales.order", "credit_override", "sales"),
    ("sales.delivery:read", "sales.delivery", "read", "sales"),
    ("sales.delivery:create", "sales.delivery", "create", "sales"),
    ("sales.delivery:update", "sales.delivery", "update", "sales"),
    ("sales.delivery:ship", "sales.delivery", "ship", "sales"),
    ("sales.invoice:read", "sales.invoice", "read", "sales"),
    ("sales.invoice:create", "sales.invoice", "create", "sales"),
    ("sales.invoice:update", "sales.invoice", "update", "sales"),
    ("sales.invoice:submit", "sales.invoice", "submit", "sales"),
    ("sales.invoice:approve", "sales.invoice", "approve", "sales"),
    ("sales.invoice:post", "sales.invoice", "post", "sales"),
    ("sales.invoice:cancel", "sales.invoice", "cancel", "sales"),
    ("sales.return:read", "sales.return", "read", "sales"),
    ("sales.return:create", "sales.return", "create", "sales"),
    ("sales.return:update", "sales.return", "update", "sales"),
    ("sales.return:submit", "sales.return", "submit", "sales"),
    ("sales.return:approve", "sales.return", "approve", "sales"),
    ("sales.return:receive", "sales.return", "receive", "sales"),
    ("sales.return:post", "sales.return", "post", "sales"),
    ("sales.pricing:manage", "sales.pricing", "manage", "sales"),
    ("sales.credit:manage", "sales.credit", "manage", "sales"),
    ("sales.report:read", "sales.report", "read", "sales"),
    ("sales.report:export", "sales.report", "export", "sales"),
]

SALES_EXECUTIVE_PERMISSIONS = [
    "sales.price_list:read",
    "sales.discount_rule:read",
    "sales.customer_credit:read",
    "sales.quotation:read",
    "sales.quotation:create",
    "sales.quotation:update",
    "sales.quotation:submit",
    "sales.quotation:convert",
    "sales.order:read",
    "sales.order:create",
    "sales.order:update",
    "sales.order:submit",
    "sales.order:confirm",
    "sales.order:cancel",
    "sales.delivery:read",
    "sales.delivery:create",
    "sales.delivery:update",
    "sales.delivery:ship",
    "sales.invoice:read",
    "sales.invoice:create",
    "sales.invoice:update",
    "sales.invoice:submit",
    "sales.return:read",
    "sales.return:create",
    "sales.return:update",
    "sales.return:submit",
    "sales.return:receive",
    "sales.report:read",
]

SALES_MANAGER_PERMISSIONS = SALES_EXECUTIVE_PERMISSIONS + [
    "sales.price_list:create",
    "sales.price_list:update",
    "sales.price_list:delete",
    "sales.discount_rule:create",
    "sales.discount_rule:update",
    "sales.discount_rule:delete",
    "sales.discount_rule:submit",
    "sales.discount_rule:approve",
    "sales.customer_credit:create",
    "sales.customer_credit:update",
    "sales.quotation:delete",
    "sales.quotation:approve",
    "sales.quotation:reject",
    "sales.order:delete",
    "sales.order:credit_override",
    "sales.invoice:approve",
    "sales.invoice:cancel",
    "sales.return:approve",
    "sales.pricing:manage",
    "sales.credit:manage",
    "sales.report:export",
]

FINANCE_REVIEWER_PERMISSIONS = [
    "sales.customer_credit:read",
    "sales.customer_credit:create",
    "sales.customer_credit:update",
    "sales.credit:manage",
    "sales.invoice:read",
    "sales.invoice:approve",
    "sales.invoice:post",
    "sales.invoice:cancel",
    "sales.return:read",
    "sales.return:approve",
    "sales.return:post",
    "sales.report:read",
    "sales.report:export",
]
