"""Organization permission constants."""

ORGANIZATION_PERMISSIONS: list[tuple[str, str, str, str]] = [
    ("organization.company:read", "organization.company", "read", "organization"),
    ("organization.company:create", "organization.company", "create", "organization"),
    ("organization.company:update", "organization.company", "update", "organization"),
    ("organization.company:delete", "organization.company", "delete", "organization"),
    ("organization.branch:read", "organization.branch", "read", "organization"),
    ("organization.branch:create", "organization.branch", "create", "organization"),
    ("organization.branch:update", "organization.branch", "update", "organization"),
    ("organization.branch:delete", "organization.branch", "delete", "organization"),
    ("organization.department:read", "organization.department", "read", "organization"),
    ("organization.department:create", "organization.department", "create", "organization"),
    ("organization.department:update", "organization.department", "update", "organization"),
    ("organization.department:delete", "organization.department", "delete", "organization"),
    ("organization.business_unit:read", "organization.business_unit", "read", "organization"),
    ("organization.business_unit:create", "organization.business_unit", "create", "organization"),
    ("organization.business_unit:update", "organization.business_unit", "update", "organization"),
    ("organization.business_unit:delete", "organization.business_unit", "delete", "organization"),
    ("organization.location:read", "organization.location", "read", "organization"),
    ("organization.location:create", "organization.location", "create", "organization"),
    ("organization.location:update", "organization.location", "update", "organization"),
    ("organization.location:delete", "organization.location", "delete", "organization"),
    ("organization.cost_center:read", "organization.cost_center", "read", "organization"),
    ("organization.cost_center:create", "organization.cost_center", "create", "organization"),
    ("organization.cost_center:update", "organization.cost_center", "update", "organization"),
    ("organization.cost_center:delete", "organization.cost_center", "delete", "organization"),
    ("organization.profit_center:read", "organization.profit_center", "read", "organization"),
    ("organization.profit_center:create", "organization.profit_center", "create", "organization"),
    ("organization.profit_center:update", "organization.profit_center", "update", "organization"),
    ("organization.profit_center:delete", "organization.profit_center", "delete", "organization"),
]
