"""Inventory permission constants per ERD_07 §16.1."""

INV_PERMISSIONS: list[tuple[str, str, str, str]] = [
    ("inventory.stock:read", "inventory.stock", "read", "inventory"),
    ("inventory.stock:export", "inventory.stock", "export", "inventory"),
    ("inventory.bin:read", "inventory.bin", "read", "inventory"),
    ("inventory.bin:create", "inventory.bin", "create", "inventory"),
    ("inventory.bin:update", "inventory.bin", "update", "inventory"),
    ("inventory.batch:read", "inventory.batch", "read", "inventory"),
    ("inventory.batch:create", "inventory.batch", "create", "inventory"),
    ("inventory.batch:update", "inventory.batch", "update", "inventory"),
    ("inventory.serial:read", "inventory.serial", "read", "inventory"),
    ("inventory.serial:create", "inventory.serial", "create", "inventory"),
    ("inventory.serial:update", "inventory.serial", "update", "inventory"),
    ("inventory.reservation:read", "inventory.reservation", "read", "inventory"),
    ("inventory.reservation:create", "inventory.reservation", "create", "inventory"),
    ("inventory.reservation:release", "inventory.reservation", "release", "inventory"),
    ("inventory.transfer:read", "inventory.transfer", "read", "inventory"),
    ("inventory.transfer:create", "inventory.transfer", "create", "inventory"),
    ("inventory.transfer:update", "inventory.transfer", "update", "inventory"),
    ("inventory.transfer:submit", "inventory.transfer", "submit", "inventory"),
    ("inventory.transfer:approve", "inventory.transfer", "approve", "inventory"),
    ("inventory.transfer:ship", "inventory.transfer", "ship", "inventory"),
    ("inventory.transfer:receive", "inventory.transfer", "receive", "inventory"),
    ("inventory.adjustment:read", "inventory.adjustment", "read", "inventory"),
    ("inventory.adjustment:create", "inventory.adjustment", "create", "inventory"),
    ("inventory.adjustment:update", "inventory.adjustment", "update", "inventory"),
    ("inventory.adjustment:submit", "inventory.adjustment", "submit", "inventory"),
    ("inventory.adjustment:approve", "inventory.adjustment", "approve", "inventory"),
    ("inventory.adjustment:post", "inventory.adjustment", "post", "inventory"),
    ("inventory.cycle_count:read", "inventory.cycle_count", "read", "inventory"),
    ("inventory.cycle_count:create", "inventory.cycle_count", "create", "inventory"),
    ("inventory.cycle_count:update", "inventory.cycle_count", "update", "inventory"),
    ("inventory.cycle_count:submit", "inventory.cycle_count", "submit", "inventory"),
    ("inventory.cycle_count:approve", "inventory.cycle_count", "approve", "inventory"),
    ("inventory.cycle_count:post", "inventory.cycle_count", "post", "inventory"),
    ("inventory.valuation:read", "inventory.valuation", "read", "inventory"),
    ("inventory.valuation:run", "inventory.valuation", "run", "inventory"),
    ("inventory.reorder_policy:read", "inventory.reorder_policy", "read", "inventory"),
    ("inventory.reorder_policy:create", "inventory.reorder_policy", "create", "inventory"),
    ("inventory.reorder_policy:update", "inventory.reorder_policy", "update", "inventory"),
    ("inventory.report:read", "inventory.report", "read", "inventory"),
    ("inventory.report:export", "inventory.report", "export", "inventory"),
]

WAREHOUSE_EXECUTIVE_PERMISSIONS = [
    "inventory.stock:read",
    "inventory.bin:read",
    "inventory.bin:create",
    "inventory.bin:update",
    "inventory.batch:read",
    "inventory.batch:create",
    "inventory.batch:update",
    "inventory.serial:read",
    "inventory.serial:create",
    "inventory.serial:update",
    "inventory.reservation:read",
    "inventory.transfer:read",
    "inventory.transfer:create",
    "inventory.transfer:update",
    "inventory.transfer:submit",
    "inventory.transfer:ship",
    "inventory.transfer:receive",
    "inventory.adjustment:read",
    "inventory.adjustment:create",
    "inventory.adjustment:update",
    "inventory.adjustment:submit",
    "inventory.cycle_count:read",
    "inventory.cycle_count:create",
    "inventory.cycle_count:update",
    "inventory.cycle_count:submit",
    "inventory.reorder_policy:read",
    "inventory.report:read",
]

WAREHOUSE_MANAGER_PERMISSIONS = WAREHOUSE_EXECUTIVE_PERMISSIONS + [
    "inventory.transfer:approve",
    "inventory.cycle_count:approve",
    "inventory.adjustment:approve",
    "inventory.reservation:create",
    "inventory.reservation:release",
    "inventory.stock:export",
    "inventory.report:export",
]

INVENTORY_CONTROLLER_PERMISSIONS = WAREHOUSE_MANAGER_PERMISSIONS + [
    "inventory.adjustment:post",
    "inventory.cycle_count:post",
    "inventory.valuation:read",
    "inventory.valuation:run",
    "inventory.reorder_policy:create",
    "inventory.reorder_policy:update",
]
