"""Low-Code permission constants — Phase 1–4."""

LOWCODE_PERMISSIONS: list[tuple[str, str, str, str]] = [
    ("lowcode.category:read", "lowcode.category", "read", "lowcode"),
    ("lowcode.category:create", "lowcode.category", "create", "lowcode"),
    ("lowcode.category:update", "lowcode.category", "update", "lowcode"),
    ("lowcode.category:delete", "lowcode.category", "delete", "lowcode"),
    ("lowcode.category:archive", "lowcode.category", "archive", "lowcode"),
    ("lowcode.category:restore", "lowcode.category", "restore", "lowcode"),
    ("lowcode.definition:read", "lowcode.definition", "read", "lowcode"),
    ("lowcode.definition:create", "lowcode.definition", "create", "lowcode"),
    ("lowcode.definition:update", "lowcode.definition", "update", "lowcode"),
    ("lowcode.definition:archive", "lowcode.definition", "archive", "lowcode"),
    ("lowcode.definition:restore", "lowcode.definition", "restore", "lowcode"),
    ("lowcode.version:read", "lowcode.version", "read", "lowcode"),
    ("lowcode.version:create", "lowcode.version", "create", "lowcode"),
    ("lowcode.version:update", "lowcode.version", "update", "lowcode"),
    ("lowcode.version:publish", "lowcode.version", "publish", "lowcode"),
    ("lowcode.version:retire", "lowcode.version", "retire", "lowcode"),
    ("lowcode.version:clone", "lowcode.version", "clone", "lowcode"),
    ("lowcode.version:validate", "lowcode.version", "validate", "lowcode"),
    ("lowcode.section:read", "lowcode.section", "read", "lowcode"),
    ("lowcode.section:create", "lowcode.section", "create", "lowcode"),
    ("lowcode.section:update", "lowcode.section", "update", "lowcode"),
    ("lowcode.section:delete", "lowcode.section", "delete", "lowcode"),
    ("lowcode.field:read", "lowcode.field", "read", "lowcode"),
    ("lowcode.field:create", "lowcode.field", "create", "lowcode"),
    ("lowcode.field:update", "lowcode.field", "update", "lowcode"),
    ("lowcode.field:delete", "lowcode.field", "delete", "lowcode"),
    ("lowcode.structure:validate", "lowcode.structure", "validate", "lowcode"),
    ("lowcode.component:read", "lowcode.component", "read", "lowcode"),
    ("lowcode.component:create", "lowcode.component", "create", "lowcode"),
    ("lowcode.component:update", "lowcode.component", "update", "lowcode"),
    ("lowcode.component:archive", "lowcode.component", "archive", "lowcode"),
    ("lowcode.component:restore", "lowcode.component", "restore", "lowcode"),
    ("lowcode.component_version:read", "lowcode.component_version", "read", "lowcode"),
    ("lowcode.component_version:create", "lowcode.component_version", "create", "lowcode"),
    ("lowcode.component_version:update", "lowcode.component_version", "update", "lowcode"),
    ("lowcode.component_version:publish", "lowcode.component_version", "publish", "lowcode"),
    ("lowcode.component_version:retire", "lowcode.component_version", "retire", "lowcode"),
    ("lowcode.component_version:clone", "lowcode.component_version", "clone", "lowcode"),
    ("lowcode.data_source:read", "lowcode.data_source", "read", "lowcode"),
    ("lowcode.data_source:create", "lowcode.data_source", "create", "lowcode"),
    ("lowcode.data_source:update", "lowcode.data_source", "update", "lowcode"),
    ("lowcode.data_source:archive", "lowcode.data_source", "archive", "lowcode"),
    ("lowcode.data_source:restore", "lowcode.data_source", "restore", "lowcode"),
    ("lowcode.data_source:activate", "lowcode.data_source", "activate", "lowcode"),
    ("lowcode.data_source:retire", "lowcode.data_source", "retire", "lowcode"),
    ("lowcode.expression:read", "lowcode.expression", "read", "lowcode"),
    ("lowcode.expression:create", "lowcode.expression", "create", "lowcode"),
    ("lowcode.expression:update", "lowcode.expression", "update", "lowcode"),
    ("lowcode.expression:archive", "lowcode.expression", "archive", "lowcode"),
    ("lowcode.expression:restore", "lowcode.expression", "restore", "lowcode"),
    ("lowcode.expression:publish", "lowcode.expression", "publish", "lowcode"),
    ("lowcode.expression:retire", "lowcode.expression", "retire", "lowcode"),
    ("lowcode.expression_binding:read", "lowcode.expression_binding", "read", "lowcode"),
    ("lowcode.expression_binding:create", "lowcode.expression_binding", "create", "lowcode"),
    ("lowcode.expression_binding:update", "lowcode.expression_binding", "update", "lowcode"),
    ("lowcode.expression_binding:delete", "lowcode.expression_binding", "delete", "lowcode"),
    ("lowcode.event_handler:read", "lowcode.event_handler", "read", "lowcode"),
    ("lowcode.event_handler:create", "lowcode.event_handler", "create", "lowcode"),
    ("lowcode.event_handler:update", "lowcode.event_handler", "update", "lowcode"),
    ("lowcode.event_handler:delete", "lowcode.event_handler", "delete", "lowcode"),
    ("lowcode.localization:read", "lowcode.localization", "read", "lowcode"),
    ("lowcode.localization:create", "lowcode.localization", "create", "lowcode"),
    ("lowcode.localization:update", "lowcode.localization", "update", "lowcode"),
    ("lowcode.localization:delete", "lowcode.localization", "delete", "lowcode"),
    ("lowcode.localization:publish", "lowcode.localization", "publish", "lowcode"),
    ("lowcode.localization:retire", "lowcode.localization", "retire", "lowcode"),
    ("lowcode.page:read", "lowcode.page", "read", "lowcode"),
    ("lowcode.page:create", "lowcode.page", "create", "lowcode"),
    ("lowcode.page:update", "lowcode.page", "update", "lowcode"),
    ("lowcode.page:archive", "lowcode.page", "archive", "lowcode"),
    ("lowcode.page:restore", "lowcode.page", "restore", "lowcode"),
    ("lowcode.page_version:read", "lowcode.page_version", "read", "lowcode"),
    ("lowcode.page_version:create", "lowcode.page_version", "create", "lowcode"),
    ("lowcode.page_version:update", "lowcode.page_version", "update", "lowcode"),
    ("lowcode.page_version:publish", "lowcode.page_version", "publish", "lowcode"),
    ("lowcode.page_version:retire", "lowcode.page_version", "retire", "lowcode"),
    ("lowcode.page_version:clone", "lowcode.page_version", "clone", "lowcode"),
    ("lowcode.page_region:read", "lowcode.page_region", "read", "lowcode"),
    ("lowcode.page_region:create", "lowcode.page_region", "create", "lowcode"),
    ("lowcode.page_region:update", "lowcode.page_region", "update", "lowcode"),
    ("lowcode.page_region:delete", "lowcode.page_region", "delete", "lowcode"),
    ("lowcode.publish_history:read", "lowcode.publish_history", "read", "lowcode"),
    ("lowcode.runtime_submission:read", "lowcode.runtime_submission", "read", "lowcode"),
    ("lowcode.runtime_submission:create", "lowcode.runtime_submission", "create", "lowcode"),
    ("lowcode.runtime_submission:update", "lowcode.runtime_submission", "update", "lowcode"),
    ("lowcode.preview_session:read", "lowcode.preview_session", "read", "lowcode"),
    ("lowcode.preview_session:create", "lowcode.preview_session", "create", "lowcode"),
    ("lowcode.preview_session:close", "lowcode.preview_session", "close", "lowcode"),
    ("lowcode.preview_session:expire", "lowcode.preview_session", "expire", "lowcode"),
]

_ALL = [p[0] for p in LOWCODE_PERMISSIONS]

LOWCODE_ADMIN_PERMISSIONS = list(_ALL)

FORM_DESIGNER_PERMISSIONS = [
    p
    for p in _ALL
    if ":publish" not in p and ":retire" not in p and ":delete" not in p
]

FORM_PUBLISHER_PERMISSIONS = [
    p
    for p in _ALL
    if any(
        x in p
        for x in (
            ":read",
            ":publish",
            ":retire",
            ":validate",
            "lowcode.definition:update",
            "lowcode.definition:archive",
            "lowcode.definition:restore",
            "lowcode.category:read",
            "lowcode.section:read",
            "lowcode.field:read",
            "lowcode.structure:validate",
            "lowcode.component:read",
            "lowcode.component:update",
            "lowcode.component:archive",
            "lowcode.component:restore",
            "lowcode.component_version:read",
            "lowcode.data_source:read",
            "lowcode.data_source:activate",
            "lowcode.data_source:retire",
            "lowcode.data_source:archive",
            "lowcode.data_source:restore",
            "lowcode.expression:read",
            "lowcode.expression_binding:read",
            "lowcode.event_handler:read",
            "lowcode.localization:read",
            "lowcode.page:read",
            "lowcode.page:update",
            "lowcode.page:archive",
            "lowcode.page:restore",
            "lowcode.page_version:read",
            "lowcode.page_region:read",
            "lowcode.publish_history:read",
            "lowcode.runtime_submission:read",
            "lowcode.preview_session:read",
        )
    )
]

LOWCODE_AUDITOR_PERMISSIONS = [p for p in _ALL if ":read" in p]
